# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "35892f24b2856f9d3de4914a939f8a98"
name = "SAR Bundle"
application_url = "https://sar-bundle.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  uri = "/webhooks/compliance"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "products/update" ]
  uri = "/webhooks/products/update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_files,read_orders,read_products,write_files,write_products"

[auth]
redirect_urls = [ "https://sar-bundle.vercel.app/auth/callback" ]

[app_proxy]
url = "https://sar-bundle.vercel.app/apps/sar-bundle"
subpath = "sar-bundle"
prefix = "apps"
