import type { MetaFunction } from "@remix-run/node";

export const meta: MetaFunction = () => {
  return [
    { title: "Privacy Policy - SAR Bundle" },
    { name: "description", content: "Privacy policy for SAR Bundle Shopify application." },
  ];
};

export default function PrivacyPolicy() {
  return (
    <div style={{ fontFamily: "Inter, sans-serif", padding: "40px", maxWidth: "800px", margin: "0 auto", color: "#333", lineHeight: "1.6" }}>
      <h1 style={{ fontSize: "2.5rem", marginBottom: "20px" }}>Privacy Policy</h1>
      <p style={{ color: "#666", marginBottom: "30px" }}>Last updated: April 07, 2026</p>

      <section style={{ marginBottom: "30px" }}>
        <h2>1. Introduction</h2>
        <p>
          SAR Bundle ("we", "our", or "us") provides a product bundling application for Shopify merchants.
          This Privacy Policy explains how we collect, use, and disclose information from merchants who install our app and their customers.
        </p>
      </section>

      <section style={{ marginBottom: "30px" }}>
        <h2>2. Information We Collect</h2>
        <p>When you install the SAR Bundle app, we automatically access certain information from your Shopify account:</p>
        <ul>
          <li><strong>Store Information:</strong> Shop name, email, domain, and currency.</li>
          <li><strong>Product Information:</strong> To display products in the bundle builder.</li>
          <li><strong>Order Information:</strong> To track revenue generated by bundles (required for our usage-based billing model).</li>
        </ul>
      </section>

      <section style={{ marginBottom: "30px" }}>
        <h2>3. How We Use Your Information</h2>
        <p>We use the collected information to:</p>
        <ul>
          <li>Provide and maintain the application's core functionality.</li>
          <li>Accurately calculate usage-based billing thresholds (200€ and 1200€ tiers).</li>
          <li>Improve the application experience and provide support.</li>
        </ul>
      </section>

      <section style={{ marginBottom: "30px" }}>
        <h2>4. Data Sharing & Disclosure</h2>
        <p>
          We do not sell your personal data. We only share information with third parties (like Shopify)
          as necessary to provide the service or comply with legal obligations.
        </p>
      </section>

      <section style={{ marginBottom: "30px" }}>
        <h2>5. Your Rights</h2>
        <p>
          Merchants can request the deletion of their data or their customers' data through Shopify's mandatory privacy webhooks,
          which our application fully supports.
        </p>
      </section>

      <section style={{ marginBottom: "30px" }}>
        <h2>6. Contact Us</h2>
        <p>
          If you have any questions about this Privacy Policy, please contact us at: <strong>[EMAIL_ADDRESS]</strong>
        </p>
      </section>

      <footer style={{ marginTop: "50px", borderTop: "1px solid #eee", paddingTop: "20px", textAlign: "center", color: "#999" }}>
        &copy; 2026 SAR Bundle. All rights reserved.
      </footer>
    </div>
  );
}
